import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Card } from "@/components/ui/card";
import Filters from "@/components/Filters";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-teal-50`}>
        <main className="container mx-auto flex flex-col justify-start gap-8">
          <Header />
          <Filters />
          <Card className="w-full h-96">{children}</Card>
        </main>
      </body>
    </html>
  );
}
